name: Test Github Actions

on: push

jobs:
    npm-build:
        runs-on: ubuntu-latest
        steps:
        - run: pwd
        - run: curl -fsSL https://bun.sh/install | bash
        - run: sudo shutdown -r now
        - run: bun --version
        - run: bun install
        - run: bun run build
