# 工作流名称
name: Test Github Actions

# 当git触发push操作时工作
on: push

# 添加权限
permissions:
    contents: write # 添加写权限，可以将打包后的文件写到下面自定义的git分支上

jobs:
    job-build:
        name: 打包任务
        runs-on: ubuntu-latest # 运行环境

        steps:
            - name: 读取仓库内容
              uses: actions/checkout@v4 # 添加actions/checkout后可以读取到自己仓库的内容

            - name: 安装bun
              uses: oven-sh/setup-bun@v2
              with:
                bun-version: latest

            - name: 查看bun版本
              run: |
                bun --version

            - name: 安装依赖并打包项目
              run: |
                bun i
                bun run build

            - name: 部署项目
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  branch: dist # 自定义分支
                  folder: dist # 构建项目后静态文件存放的目录
