name: Test Github Actions

on: push

jobs:
    npm-build:
        runs-on: ubuntu-latest
        steps:
        - run: pwd
        - run: node --version
        - run: npm i pnpm -g
        - run: pnpm --version
        - run: pnpm i
        - run: pnpm run build
