name: Test Github Actions

on: push

permissions:
    contents: write

jobs:
    job-build:
        name: 打包任务
        runs-on: ubuntu-latest

        steps:
            - name: 读取仓库内容
              uses: actions/checkout@v4

            - name: 安装pnpm
              run: |
                npm i pnpm -g
                pnpm --version

            - name: 安装依赖并打包项目
              run: |
                pnpm i
                pnpm run build

            - name: 部署项目
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  branch: dist
                  folder: dist
